# Generated by Django 4.2.6 on 2024-01-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_estagiario_orientador_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='biografia',
            field=models.CharField(blank=True, max_length=50, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='user',
            name='outrasinformacoes',
            field=models.CharField(blank=True, max_length=500, verbose_name='OutrasInformacoes'),
        ),
    ]
