# Generated by Django 4.2.6 on 2024-01-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_biografia_alter_user_outrasinformacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
