# Generated by Django 4.2.6 on 2023-10-24 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_orientador'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='data_final',
            field=models.DateField(blank=True, null=True, verbose_name='Data Final'),
        ),
        migrations.CreateModel(
            name='EstagiarioProfile',
            fields=[
                ('estagiario_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_nascimento', models.DateField(verbose_name='Nascimento')),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Telefone')),
                ('orientador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estagiarios', to='core.orientador', verbose_name='Orientador')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
