# Generated by Django 4.2.6 on 2024-01-11 12:17

import core.models.users
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='padrao.png', upload_to=core.models.users.user_directory_path),
        ),
    ]
