# Generated by Django 4.2.6 on 2023-10-24 22:13

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_data_final_estagiarioprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estagiarioprofile',
            name='data_de_nascimento',
            field=models.DateField(blank=True, verbose_name='Nascimento'),
        ),
        migrations.AlterField(
            model_name='estagiarioprofile',
            name='orientador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estagiarios', to='core.orientador', verbose_name='Orientador'),
        ),
        migrations.AlterField(
            model_name='estagiarioprofile',
            name='telefone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Telefone'),
        ),
    ]
