# Generated by Django 4.2.6 on 2023-10-24 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_estagiarioprofile_data_de_nascimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estagiarioprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.estagiario'),
        ),
    ]
