# Generated by Django 4.2.6 on 2023-10-25 20:52

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_estagiarioprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='estagiarioprofile',
            name='ano_letivo',
            field=models.IntegerField(blank=True, default=3, verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.CreateModel(
            name='OrientadorProfile',
            fields=[
                ('orientador_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_nascimento', models.DateField(blank=True, verbose_name='Nascimento')),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Telefone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.orientador')),
            ],
        ),
    ]
