# Generated by Django 4.2.6 on 2024-01-12 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_participante_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='participante',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.participante', verbose_name='Endereço'),
        ),
    ]
