# Generated by Django 4.2.6 on 2024-01-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_endereco_participante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='username',
            field=models.CharField(max_length=100, unique=True, verbose_name='Username'),
        ),
    ]
