# Generated by Django 4.2.6 on 2023-12-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='biografia',
            field=models.CharField(default='', max_length=10, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='padrao.jpg', upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=10, unique=True, verbose_name='Username'),
        ),
    ]
