# Generated by Django 4.2.6 on 2024-01-12 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_participante_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participante',
            name='data_de_nascimento',
        ),
    ]
