# Generated by Django 4.2.6 on 2023-12-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_user_biografia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='padrao.png', upload_to='pics'),
        ),
    ]
