# Generated by Django 4.2.6 on 2024-01-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_user_image_documentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estagiario',
            name='ano_letivo',
            field=models.IntegerField(blank=True, choices=[(3, '3 Ano'), (4, '4 Ano')], default=3, verbose_name='Ano'),
        ),
    ]
