# Generated by Django 4.2.6 on 2024-01-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_estagiario_ano_letivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estagiario',
            name='ano_letivo',
            field=models.IntegerField(blank=True, choices=[(3, '3º Ano'), (4, '4º Ano')], default=3, verbose_name='Ano'),
        ),
    ]
