# Generated by Django 4.2.6 on 2023-12-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_endereco_participante_user_outrasinformacoes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='av_r',
            field=models.CharField(blank=True, max_length=300, verbose_name='AV'),
        ),
    ]
