# Generated by Django 4.2.6 on 2024-01-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_estagiario_ano_letivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
