# Generated by Django 4.2.6 on 2023-12-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_endereco_av_r'),
    ]

    operations = [
        migrations.AddField(
            model_name='participanteprofile',
            name='estagiarios',
            field=models.ManyToManyField(blank=True, related_name='participante_profiles', to='core.estagiario'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cep',
            field=models.CharField(max_length=8, verbose_name='CEP'),
        ),
    ]
