# Generated by Django 4.2.6 on 2024-01-22 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_participante_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos',
            name='pertence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.participante'),
        ),
    ]
