# Generated by Django 4.2.6 on 2023-12-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_participanteprofile_estagiarios_alter_endereco_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participanteprofile',
            name='participante_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
