# Generated by Django 4.2.6 on 2024-01-23 13:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_documentos_pertence'),
    ]

    operations = [
        migrations.CreateModel(
            name='agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_da_semana', models.IntegerField(blank=True, choices=[(0, 'DOMINGO'), (1, 'SEGUNDA'), (2, 'TERÇA'), (3, 'QUARTA'), (4, 'QUINTA'), (5, 'SEXTA'), (6, 'SABADO')], verbose_name='Semana')),
                ('horario', models.TimeField(choices=[(datetime.time(8, 10), '8:10'), (datetime.time(9, 10), '9:10'), (datetime.time(10, 10), '10:10'), (datetime.time(11, 10), '11:10'), (datetime.time(12, 10), '12:10'), (datetime.time(13, 10), '13:10'), (datetime.time(14, 10), '14:10'), (datetime.time(15, 10), '15:10'), (datetime.time(16, 10), '16:10'), (datetime.time(17, 10), '17:10'), (datetime.time(18, 10), '18:10')])),
                ('estagiario', models.ManyToManyField(blank=True, null=True, related_name='agendas_estagiario', to='core.estagiario')),
                ('participante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agendas_participante', to='core.participante')),
                ('reservadoPor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
