# Generated by Django 4.2.6 on 2024-01-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_agenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='dia_da_semana',
            field=models.IntegerField(blank=True, choices=[(0, 'SEGUNDA-FEIRA'), (1, 'TERÇA-FEIRA'), (2, 'QUARTA-FEIRA'), (3, 'QUINTA-FEIRA'), (4, 'SEXTA-FEIRA'), (5, 'SABADO'), (6, 'DOMINGO')], verbose_name='Semana'),
        ),
    ]
