# Generated by Django 4.2.6 on 2024-01-25 15:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_agenda_dia_da_semana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='dia_da_semana',
            field=models.IntegerField(blank=True, choices=[(0, 'SEGUNDA-FEIRA'), (1, 'TERÇA-FEIRA'), (2, 'QUARTA-FEIRA'), (3, 'QUINTA-FEIRA'), (4, 'SEXTA-FEIRA'), (5, 'SÁBADO'), (6, 'DOMINGO')], verbose_name='Semana'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='horario',
            field=models.TimeField(choices=[(datetime.time(8, 10), '8:10'), (datetime.time(9, 10), '9:10'), (datetime.time(10, 10), '10:10'), (datetime.time(11, 10), '11:10'), (datetime.time(12, 10), '12:10'), (datetime.time(13, 10), '13:10'), (datetime.time(14, 10), '14:10'), (datetime.time(15, 10), '15:10'), (datetime.time(16, 10), '16:10'), (datetime.time(17, 10), '17:10')]),
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
