# Generated by Django 4.2.6 on 2024-01-30 11:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_agenda_dia_da_semana_alter_agenda_horario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Atendimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atendimento', models.DateTimeField(verbose_name='Data do Atendimento')),
                ('motivoFalta', models.CharField(max_length=100, verbose_name='Motivo da Falta')),
                ('presenca', models.BooleanField(default=False)),
                ('estagiario', models.ManyToManyField(related_name='atendimentos', to='core.estagiario')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.participante')),
            ],
        ),
    ]
