# Generated by Django 4.2.6 on 2024-01-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_useractivity_last_activity_atendimentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimentos',
            name='motivoFalta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Motivo da Falta'),
        ),
    ]
