# Generated by Django 4.2.6 on 2024-01-31 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_atendimentos_ocorreu'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='qtd_atendimentos',
            field=models.IntegerField(default=0),
        ),
    ]
