# Generated by Django 4.2.6 on 2024-01-31 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_responsavel_remove_participante_estagiarios_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participante',
            name='responsavel',
        ),
        migrations.AddField(
            model_name='responsavel',
            name='participante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.participante'),
        ),
    ]
