# Generated by Django 4.2.6 on 2024-02-01 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_participante_responsavel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsavel',
            name='participante',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.participante'),
        ),
    ]
