# Generated by Django 4.2.6 on 2024-02-01 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_responsavel_participante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='participante',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agendas_participante', to='core.participante'),
        ),
    ]
