# Generated by Django 4.2.6 on 2024-03-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_agenda_participante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estagiario',
            name='telefone',
            field=models.CharField(blank=True, max_length=11, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='orientador',
            name='data_de_nascimento',
            field=models.DateField(blank=True, verbose_name='Data De Nascimento'),
        ),
        migrations.AlterField(
            model_name='orientador',
            name='telefone',
            field=models.CharField(blank=True, max_length=11, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='telefone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='telefone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='biografia',
            field=models.CharField(blank=True, max_length=50, verbose_name='Biografia'),
        ),
        migrations.AlterField(
            model_name='user',
            name='outrasinformacoes',
            field=models.CharField(blank=True, max_length=500, verbose_name='Outras Informações'),
        ),
    ]
